### ISSUE TITLE
클라스 로그인 창 Caps Lock 유무

### ISSUE THREAD

**Issue by maple-maelin** [klas-helper/klas-helper#41]
클라스 로그인 창에 접속하면 가끔 Caps Lock 유무를 확인 못해서 로그인하는데 비밀번호를 잘 못 입력하는 경우가 발생해서, Caps Lock 유무가 나타나게 하게끔 문구로 표시하는게 어떨까 싶은데, 이 점은 혹시 개선 가능하나요?

**Comment by hyunsungyoo** [comment]
요즘 키보드에 Caps Lock 유무가 뜨는 제품이 많은데 그런 제품으  쓰시면 되지않을까요?

**Comment by hyunsungyoo** [comment]
요즘 키보드에 Caps Lock 유무가 뜨는 제품이 많은데 그런 제품을 쓰시면 되지않을까요?

**Comment by maple-maelin** [comment]
그것도 좋긴 하지만, 그렇게 생각하시면 뭐 어쩔수 없는데, 근데 이런 기능이 좀 더 추가되면 좋지 않을까 싶어서 제안하게 되었어요!

**Comment by mirusu400** [comment]
다음 업데이트때 반영될 예정입니다
