### ISSUE TITLE
강의영상 다운로드 관련 문제

### ISSUE THREAD

**Issue by KyuhcH** [klas-helper/klas-helper#80]
몇몇 교수님은 온라인 강의에서 얼굴 화면이나 다른 화면과 분할하여 강의가 올라옵니다. 이런 강의는 오디오 다운로드만 가능하고 두 분할 화면 중 하나만 다운 가능합니다. 제가 수강 중인 강의 영상에서는 교수님 캠화면만 다운로드할 수 있어 불편합니다.
분할 화면 온라인 강의에서는 두 화면 중 한 개를 선택해서 다운로드할 수 있는 기능이 있으면 좋겠습니다.

**Comment by mirusu400** [comment]
강의가 두개로 분할된 경우는 두가지 경우입니다.
1. 실제로 강의가 분할되어 있을때 #2 
2. 강의 슬라이드와, 교수님의 목소리 혹은 캠 영상 두개가 띄워져 있을때 #14

둘다 중복으로 제보된 문제이며, 1번 문제의 경우 이미  분할된 동영상을 모두 다운로드 받게끔 조치가 되어있습니다.

후자의 경우 슬라이드(이미지)방식이기 때문에 이를 영상화 해서 다운로드 받는건 현재 스크립트 상으론 무리가 있고, 추후 확장 프로그램으로 마이그레이션 진행 시 슬라이드 파일들을 이미지 화 해서 압축 파일로 다운로드 가능하게끔 제공해볼 예정입니다.

혹시 다른 케이스라면, 정확한 제보 부탁드리겠습니다~
