### ISSUE TITLE
갑자기 적용이 안되네요

### ISSUE THREAD

**Issue by christayod** [klas-helper/klas-helper#82]
갑자기 방금 전부터 적용이 안되는데 이유를 모르겠네요 따로 건드린 것도 없는데 인터넷이 느린 것도 아니고

**Comment by nbsp1221** [comment]
GitHub 저장소의 소유권을 옮기는 과정에서 URL 주소가 변경되는 것을 인지하지 못해 일어난 실수가 원인이었고 현재는 해결된 상황입니다.
유저 스크립트를 업데이트하시면 정상적으로 이용하실 수 있습니다.
