### ISSUE TITLE
학기 중에 계절학기 과목이 우선적으로 시간표에 뜨지 않도록 하는 방법이 있을까요?

### ISSUE THREAD

**Issue by ForrestLIM** [klas-helper/klas-helper#83]
계절학기 수강신청을 한 경우, 클라스 자체 시간표에서 학기중임에도 불구하고 계절 수업 시간표가 먼저 뜨는데요.
수강과목현황을 확인하기 위해 클라스에 접속할 때마다 학기를 바꿔주어야 하는 번거로움이 있습니다.

혹시 클라스헬퍼 기능으로 특정 학기 시간표를 고정하고, 더불어 수강과목현황에 고정된 시간표의 내역이 뜨도록 할 수 있을까요?

**Comment by mirusu400** [comment]
![image](https://user-images.githubusercontent.com/25397908/143587489-f63edd26-3a6d-4f46-9f4f-8e121c3d2c10.png)

안녕하세요. 혹시 자체 시간표라는게 위 이미지에서 3학기로 먼저 나온다는거 맞으신가요?

애초에 klas-helper 유저스크립트는 캐시 기능이 없기 때문에, 계절학기가 시작하기 전 이전 학기 시간표가 나오는건 가능하지만 특정 학기 시간표를 `고정`하는건 힘들어 보입니다. 좀 더 고려해보고 구현이 필요하겠다 싶으면 [확장 프로그램](https://github.com/klas-helper/klas-helper-extension) 버전에서 구현을 해보도록 하겠습니다.

**Comment by ForrestLIM** [comment]
![제목 없음](https://user-images.githubusercontent.com/58320075/143617226-b60da737-f45e-4c89-81c0-6c928a63943e.png)

네. 겨울 계절학기라 4학기가 먼저 나옵니다. 
매번 학기를 눌러서 변경해주기가 귀찮아서 의견 드렸어요. 감사합니다.

**Comment by mirusu400** [comment]
![image](https://user-images.githubusercontent.com/25397908/144747411-ba419796-2ce3-4338-8f25-b1b4b5b25d2c.png)

https://github.com/klas-helper/klas-helper-extension
확장 프로그램 버전에서 해당 기능을 추가했습니다. 빠른 시일 내 업데이트 예정입니다.
