### ISSUE TITLE
KLAS-helper README file 중국어 추가

### ISSUE THREAD

**Issue by swpang10** [klas-helper/klas-helper#85]
KLAS-helper README file 중국어 추가
간체자와 번체자 따로 번역하였습니다
[README-CN.md](https://github.com/klas-helper/klas-helper/files/7651788/README-CN.md)
[README-CN(简体字).md](https://github.com/klas-helper/klas-helper/files/7651789/README-CN.md)

**Comment by OctopusET** [comment]
@swpang10 직접 PR을 올려 주시는게 좋겠습니다.
git 사용이 어렵다면 메인페이지에서 Add file -> Create new file 을 통해 추가 하고 PR을 올려주실 수 있습니다.

![capture](https://user-images.githubusercontent.com/18513799/144730389-f5c673fe-f0a7-44e9-8ec5-d7a7bdfa328c.png)

Related issues: #86 #87 #88
