### ISSUE TITLE
시간표 오류

### ISSUE THREAD

**Issue by ahmola** [klas-helper/klas-helper#89]
안녕하세요. klas helper를 사용중인 학생입니다. 시간표에 수업 시간도 표시가 되도록하는 기능에서 오류가 있는 것 같습니다. 교시마다 시간 표시가 제대로 되지 않는 오류가 있습니다(3교시를 13:30 ~ 15:00시로 표시됨). 제가 이번에 시험볼 때 해당 오류로 인해 피해를 봐서 다른 학생분들도 피해를 보지 않았으며 하는 마음에 올려봅니다.

**Comment by mirusu400** [comment]
확인 후 수정하였습니다. (확장 프로그램은 베타 버전 혹은 며칠 뒤면 자동으로 업데이트 됩니다.) 타임테이블 생성 알고리즘이 독특해서 버그가 많네요 ㅠㅠ
