### ISSUE TITLE
온라인 강의 항목에 과제 기한이 표시되는 문제

### ISSUE THREAD

**Issue by grayroom** [klas-helper/klas-helper#91]
**klas 강의목록에 과제가 함께 표시되어있는 탓에 아래와 같은 문제가 발생합니다.**

<img width="713" alt="스크린샷 2022-05-15 오후 10 41 17" src="https://user-images.githubusercontent.com/43588644/168475914-2c3cb0dd-d33c-4281-aeb9-a6a073a28e95.png">

- 강의목록에 남아있는 항목이 총 5개입니다(과제:1 / 강의:4)
<img width="199" alt="스크린샷 2022-05-15 오후 10 42 28" src="https://user-images.githubusercontent.com/43588644/168475963-1a995103-f0f7-4f05-8791-af4a35b2ccdc.png">

 - "4개의 강의 중 1개가 1일 후 마감입니다" 라고 표시됩니다.
 - 강의 갯수는 잘 세는것 같은데, 가장 임박한 due date를 과제에서도 가져오는것 같습니다.

**Comment by grayroom** [comment]
아래 기한이짧은 강의가 있었네요ㅠ

**Comment by vtd201** [comment]
But it's not me? I mean i dont study it

Vào Th 2, 16 thg 5, 2022 lúc 03:09 JeongHoon Lee ***@***.***>
đã viết:
